version: "3.8"

services:
  webserver:
    image: nginx:1.24.0-bullseye
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./nginx/ssl/:/etc/nginx/ssl/:ro
      - ./nginx/www/:/var/www/:ro
  game:
    build: .
    env_file:
      - .env
    expose: 
      - "8000"
    depends_on:
      - db
    volumes:
      - ./nginx/www/:/app/staticfiles/:rw
  db:
    image: postgres:16.1-bullseye
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - "5432"

volumes:
  postgres_data: