version: 3.9

services:
  web:
    build: .
    args:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    expose: 
      - "8000"
  db:
    image: postgres:16.1-bullseye
    args:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - "5432"