# Generated by Django 4.2.6 on 2023-11-08 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=20)),
                ('nickname', models.CharField(max_length=20)),
                ('auth_secret', models.CharField(max_length=32)),
                ('wins', models.PositiveIntegerField()),
                ('loses', models.PositiveIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='YourModel',
        ),
    ]
