# Generated by Django 4.2.6 on 2023-11-10 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_usermodel_delete_yourmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='nickname',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='name',
            field=models.CharField(default='rafa', max_length=42),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='login',
            field=models.CharField(max_length=42),
        ),
    ]
