# Generated by Django 4.2.6 on 2023-11-15 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_customuser_language_alter_customuser_auth_secret'),
    ]

    operations = [
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('login', models.CharField(max_length=42)),
                ('gamemode', models.CharField(default='default', max_length=32)),
                ('match_type', models.CharField(default='default', max_length=32)),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='auth_secret',
            field=models.CharField(default='BVFTI3LP2UPIIOFZEA5D4QTOXHONFNKM', max_length=32),
        ),
    ]
