# Generated by Django 4.2.6 on 2023-11-10 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_remove_usermodel_nickname_usermodel_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='twofa_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='auth_secret',
            field=models.CharField(default='DJ7PMZCP4KV72BCJQBPJ53TID5KN6KFD', max_length=32),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='loses',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='name',
            field=models.CharField(max_length=42),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='wins',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
