# Generated by Django 4.2.6 on 2023-11-22 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_queue_alter_customuser_auth_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='match_suggested_name',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='auth_secret',
            field=models.CharField(default='DH6R4FPI23SVP3LNQO77I7UVODDRH2LG', max_length=32),
        ),
    ]
