# Generated by Django 4.2.6 on 2023-12-08 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_queue_match_suggested_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='alias',
            field=models.CharField(default='dummy', max_length=12),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='auth_secret',
            field=models.CharField(default='ZXD7YJWVSI3D26MM4XFINJMJKK6AHOVK', max_length=32),
        ),
    ]
